### ISSUE TITLE
Make view mode windows open in a new tab

### ISSUE THREAD

**Issue by mayrinck** [author-more/penpot-desktop#18]
Hello guys!

The client right now always open Penpot's view mode in a separate window, which is kinda annoying, specially for people used to the "Figma Desktop" app experience. What do you think of adding an option to only open view mode in tabs instead of new windows? I think that would be very helpful to improve the general experience of the app.

![image](https://github.com/user-attachments/assets/ff62f9ab-35b2-4f9d-9957-1d6b22479e1c)

**Comment by Belar** [comment]
Hi @mayrinck. 
Thank you for the suggestion. I’m currently working on a couple of tasks in that area, including the pop-ups (#11), and will make sure Preview mode is covered by the fixes.
