### ISSUE TITLE
[Bug] - The self-hosted instance does not load

### ISSUE THREAD

**Issue by Xenxia** [author-more/penpot-desktop#30]
Hello,

I tried to put my instance in the parameters, except that I have a tab with the name “undefined”, I have no log on the server side as if there were no request.

Otherwise with the default url it works.

I don't know where to find the software logs

Version : 0.4.2
OS : Windows

![image](https://github.com/user-attachments/assets/c4f2b241-34f0-405b-893f-2795c130bb88)

**Comment by Belar** [comment]
Hi,
I could reproduce the “undefined” tab only with an address that the Penpot Desktop cannot connect to e.g. non-existent server.

Does your instance open in a browser? Does the Penpot Desktop open `https://example.com` if it is specified as an instance?

There is no log file, but you could start Penpot Desktop from the PowerShell. It will log if there are instance registration or connection issues.

**Comment by Xenxia** [comment]
Hi @Belar ,

thank you for your reply, in fact I had a DNS problem my bad 😅 

Sorry for the inconvenience, problem solved
