### ISSUE TITLE
[Bug] - login with OpenID : does not redirect to login site

### ISSUE THREAD

**Issue by Xenxia** [author-more/penpot-desktop#31]
Hi,

This time, I'm stuck on OpenID authentication, when I click on the Penpot OpenID button nothing happens, no error log in the console, and I have a request that goes to the server but no reaction from the client.

On the browser, OpenID authentication works: I'm redirected to the login site, and after entering my credentials, I'm returned to penpot.

Version : 0.4.2
OS : Windows

Thank for you help

**Comment by Xenxia** [comment]
Hello @Belar,

Yes, I use Gitea as an OpenID provider

**Comment by Belar** [comment]
Yes, the fix wouldn’t help with a custom provider. However, there is a new feature in [0.6.0](https://github.com/author-more/penpot-desktop/releases/tag/v0.6.0) which allows you to control navigation requests that don’t fall under the predefined rules. It should let you allow opening of the authentication flow.

**Comment by Xenxia** [comment]
Hello @Belar ,

I've just tested it and it works well, thank you. 🙂
