### ISSUE TITLE
Verify Flathub ownership

### ISSUE THREAD

**Issue by Beryesa** [author-more/penpot-desktop#36]
Hi! We're live on flathub https://flathub.org/apps/com.authormore.penpotdesktop :tada:
The next step would be verifying the ownership (see https://docs.flathub.org/docs/for-app-authors/verification)
![image](https://github.com/user-attachments/assets/e685f9e1-472c-44e2-aa95-ccfcce19e65b)
_(the tokens are public anyway, nothing to hide)_

It would be great if you could update the website when you have time :P 
Thanks :D

**Comment by Belar** [comment]
That is fantastic. 🎉

I added the verification token.

**Comment by Beryesa** [comment]
Perfect, it should be updated in a few hours, thanks! :P 
![image](https://github.com/user-attachments/assets/559fba49-b960-4d51-b370-c7bc551cd118)
